### PR TITLE
[index.slim] Override height from guide's styles

### PR DESCRIPTION
**Pull request by k0nserv**
Fixes issue with mobile layout

screen shot 2015-05-31 at 21 44 21

### CODE REVIEW

**Comment by segiddins** [comment]
@k0nserv can you show us what it looks like fixed?

**Comment by k0nserv** [comment]
Sure thing

**Comment by k0nserv** [comment]
screen shot 2015-05-31 at 21 50 35
screen shot 2015-05-31 at 21 50 19
screen shot 2015-05-31 at 21 50 07

Mobile, 13 Inch non retina macbook and 24 inch 1080p monitor

**Comment by segiddins** [comment]
@k0nserv very design. such amaze.

**Pull request merged**
